name: project_muk
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.1
  http: ^0.12.0+3
  cloud_firestore: ^0.13.0+1
  transparent_image: ^1.0.0
  image_picker: 0.6.0+20
  datetime_picker_formfield: ^0.1.7
  uuid: ^2.0.2
  firebase_storage: ^3.1.1
  algolia: ^0.1.7
  firebase_auth: ^0.14.0+9
  google_maps_flutter: ^0.5.21
  location: ^2.3.5
  scoped_model: ^1.0.1
  flutter_native_splash: ^0.1.9
  get_it: ^2.0.0
  flutter_dotenv: ^2.1.0
  firebase_crashlytics: ^0.1.2
  firebase_analytics: ^5.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  logger: ^0.8.2

flutter_native_splash:
  image: assets/images/logocar.png
  color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Regular.ttf

